### ISSUE TITLE
paypal-button-container

### ISSUE THREAD

**Issue by BaotingHuang** [paypal-examples/vue-integration#2]
Cannot hide paypal-button-container when paid changed to true.

**Comment by devchristina** [comment]
Hi @BaotingHuang, is this still an issue?

**Comment by BaotingHuang** [comment]
PapPal button is still there after it is paid successfully, I have to add <p v-show="!paid" id="paypal-button-container"></p> to hide button.
here is my code as bellow.
<template>
  <div>
    <p v-show="!paid" id="paypal-button-container"></p>
    <p v-show="paid" id="confirmation">Order complete!</p>
  </div>
</template>

**Comment by daguilera1** [comment]
@BaotingHuang, sorry it seems like the code block you added in your comment isn't showing for me, can you add more details and maybe a screenshot of the issue? 😄

**Comment by BaotingHuang** [comment]
Sorry, I don't know why my code is blocked. I upload pictures as bellow.
After payment completed, the pay button should not be shown.
![button on](https://github.com/paypal-examples/vue-integration/assets/39665175/0df13bcb-8e22-4690-9249-cd08528ce469)
This picture is right, I have to add v-show after payment.
![button off](https://github.com/paypal-examples/vue-integration/assets/39665175/dbafee93-a7ed-4e33-8520-d3b58546ed9e)

**Comment by DominusKelvin** [comment]
Hey @BaotingHuang I just submitted this PR #5 that resolves the issue of the button not being hidden.

**Comment by BaotingHuang** [comment]
After payment completed, the pay button is still displayed. By the way, I use vue2 not vue3, maybe paypal-button is not supported by vue2, right?

**Comment by DominusKelvin** [comment]
> After payment completed, the pay button is still displayed. By the way, I use vue2 not vue3, maybe paypal-button is not supported by vue2, right?

The PR is submitted fix that issue once merged

**Comment by devchristina** [comment]
@DominusKelvin -- @BaotingHuang, can this issue be closed as completed?

**Comment by DominusKelvin** [comment]
> @DominusKelvin -- @BaotingHuang, can this issue be closed as completed? 

Yes it can @devchristina
